- id: '1646332350513'
  alias: Aqara Magic Cube
  description: ''
  use_blueprint:
    path: Mikkelmoeller/aqara-magic-cube-zha-51-actions.yaml
    input:
      remote: 74527e7b71aae4d90bd800527cd25318
      cube_shake:
      - service: light.toggle
        data:
          transition: 4
          color_name: coral
          brightness_pct: 40
        target:
          entity_id: light.ikea_e14_gameroom
