- id: '1646332350513'
  alias: Aqara Magic Cube
  description: ''
  use_blueprint:
    path: Mikkelmoeller/aqara-magic-cube-zha-51-actions.yaml
    input:
      remote: 74527e7b71aae4d90bd800527cd25318
      cube_shake:
      - service: light.toggle
        data:
          transition: 4
          color_name: coral
          brightness_pct: 40
        target:
          entity_id: light.ikea_e14_gameroom
- id: '1649696810971'
  alias: New Automation
  description: ''
  trigger:
  - device_id: bdc72f1122edd2f4757388f13fc590ba
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: c716be5cba86e0b7d4c712dae63e282f
    entity_id: light.ikea_e27_gameroom
    domain: light
  mode: single
