default_config:
  # resources
  - type: js,
    url: "/hacsfiles/garbage-collection-card/garbage-collection-card.js"

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

homeassistant:
  customize: !include customize.yaml
  #packages: !include_dir_named include

# Text to speech
tts:
  - platform: google_translate

panel_iframe:
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: http://homeassistant.local:8181/home

browser_mod:
  prefix: "browser_"
  
#zha:
#  zigpy_config:
#    ota:
#      ikea_provider: true # Auto update Trådfri devices
#      ledvance_provider: true # Auto update LEDVANCE/OSRAM devices
#      salus_provider: true

     
#logger:
#  default: info
#  logs:
#    homeassistant.core: debug
#    homeassistant.components.zha: debug
#    bellows.zigbee.application: debug
#    bellows.ezsp: debug
#    zigpy: debug
#    zigpy_deconz.zigbee.application: debug
#    zigpy_deconz.api: debug
#    zigpy_xbee.zigbee.application: debug
#    zigpy_xbee.api: debug
#    zigpy_zigate: debug
#    zigpy_znp: debug
#    zhaquirks: debug

anniversaries:
  sensors:
    - name: Fraser's Birthday
      date: "1992-12-07"
    - name: Julie's Birthday
      date: "1994-01-05"
    - name: Wedding Anniversary
      date: "2019-09-28"
    - name: Mum's Birthday
      date: "2020-05-29"
    - name: Caleb's Birthday
      date: "2018-10-16"
    - name: Brooke's Birthday
      date: "2010-02-01"
    - name: Lewis's Birthday
      date: "2011-11-10"
    - name: Robbie's Birthday
      date: "2009-11-26"
    - name: Zorro's Birthday
      date: "2015-02-20"
    - name: Cookie's Birthday
      date: "2018-08-19"

device_tracker:
  - platform: bt_smarthub

remote:
  - platform: broadlink
    host: 192.168.0.45
    mac: A0:43:B0:53:F7:00

counter:
  successful_prints:
    initial: 5
    step: 1

input_number:
  slider1:
    name: Cat Water Filter
    initial: 30
    min: 0
    max: 35
    step: 1
  slider2:
    name: Air Filter
    initial: 180
    min: 0
    max: 180
    step: 1
    
google:
  client_id: !secret googleclient_id
  client_secret: !secret googleclient_secret

nest:
  client_id: !secret googleclient_id
  client_secret: !secret googleclient_secret
  project_id: !secret googleproject_id
  subscriber_id: !secret googlesub_id

spotify:
  client_id: !secret spotifyid
  client_secret: !secret spotifysecret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

#Using MQTT Instead Currently
#octoprint:
#  host: 192.168.1.103
#  api_key: !secret octoprint
#  name: Ender3V2
#  number_of_tools: 2
#  sensors:
#    monitored_conditions:
#     - 'Current State'
#     - 'Job Percentage'
#     - 'Temperatures'
#     - 'Time Elapsed'
#     - 'Time Remaining'

breaking_changes:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

binary_sensor: !include include/binary_sensor.yaml
group: !include include/group.yaml
light: !include include/light.yaml
sensor: !include include/sensor.yaml
switch: !include include/switch.yaml
template: !include include/template.yaml
