
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


  
frontend:
  themes: !include_dir_merge_named themes
  
homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate
  
  
panel_iframe:
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: http://homeassistant.local:8181/home
    
#
updater:
# Sensors Go Here
sensor:
  - platform: uptime
    name: Time Online
  - platform: version
    name: HA Version

    #Steam Online
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - 76561198202177572
      - 76561198044019842
      - 76561198127082846
      - 76561198144963307

  - platform: tautulli
    api_key: !secret tautulli 
    host: localhost
    monitored_users: 
        - undamagedvirus_
    monitored_conditions:
        - Episode_Count
     
      
  - platform: systemmonitor
    resources:
      - type: disk_use
        arg: /home
      - type: memory_free
      - type: memory_use
      - type: last_boot
      - type: processor_use
      - type: processor_temperature
      
  - platform: openhardwaremonitor
    host: 192.168.0.19
  
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'UndamagedVirus/HomeAssistantConfig'

remote:
  - platform: broadlink
    host: 192.168.0.45
    mac: A0:43:B0:53:F7:00


anniversaries:
  sensors:
  - name: Fraser's Birthday
    date: '1992-12-07'
  - name: Julie's Birthday 
    date: '1994-01-05'
  - name: Wedding Anniversary
    date: '2019-09-28'
  - name: Mum's Birthday 
    date: '2020-05-29'

spotify:
  client_id: !secret spotifyid
  client_secret: !secret spotifysecret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

weather:
  - platform: darksky
    api_key: !secret darksky_key
    units: si
    mode: daily
    
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

octoprint:
  host: 192.168.0.20
  api_key: !secret octoprint
  name: Ender3V2
  number_of_tools: 2
  sensors:
    monitored_conditions:
     - 'Current State'
     - 'Job Percentage'
     - 'Temperatures'
     - 'Time Elapsed'
     - 'Time Remaining'

breaking_changes:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
