- platform: group
  name: Gaming Room Lights
  entities:
      - light.ikea_e14_gameroom
      - light.ikea_e27_gameroom

- platform: group
  name: Gaming Room Lights
  entities:
      - light.ikea_e14_master
      - light.ikea_e27_gameroom